[project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "animat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
exec = "mojo main.mojo"
clean = "magic clean"

[dependencies]
webgpu-headers = ">=0.0.0.2023.11.27.d2fec1,<0.0.0.2023.11.28"
glfw = ">=3.4,<4"
python = ">=3.11.9,<3.12"
max = "~=nightly"
wgpu-native = "22.1.0.4.*"
